### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by sosukesuzuki**

### CODE REVIEW

**Comment by pf35301** [comment]
Yay! 👍 
Thanks for refactor!
Do you mind commiting README.md that is written setup?

**Comment by pf35301** [comment]
@sosukesuzuki 
Yay! 👍 
Thanks for refactor!
Do you mind commiting README.md that is written setup?

**Comment by pf35301** [comment]
@sosukesuzuki 
I plan to accept the pull request as soon as I completely understand contents.

**Comment by sosukesuzuki** [comment]
@pf35301 
I got it. 
I'll write the setup to README.md.
Also, I deployed PrefabDocumenterPage to https://angry-darwin-42a02a.netlify.com with Netlify. Please confirm.

**Comment by sosukesuzuki** [comment]
Please choose and deploy your favorite deployment method.
I recommend [Netlify](https://www.netlify.com/).
On Netlify, you can select the repository and specify build command and the directory you want to deploy. Please refer the below if you need:
https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/

**Pull request merged**
